version: '3'

services:
  notes:
    container_name: notes
    build: ./notes
    ports:
      - "8080:80"
    networks:
      - app-network

  categories:
    container_name: categories
    build: ./categories
    ports:
      - "8081:80"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 12345
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    container_name: keycloak
    networks:
      - app-network
    command: -v start-dev

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - app-network
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_EXPLORE_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

networks:
  app-network:
    driver: bridge

volumes:
  prometheus:
    name: prometheus
  grafana-storage:
    driver: local