version: '3'

services:
  notes:
    container_name: notes
    build: ./notes
    ports:
      - "8080:80"

  categories:
    container_name: categories
    build: ./categories
    ports:
      - "8081:80"
